apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-backend
  labels:
    app: parking-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parking-backend
  template:
    metadata:
      labels:
        app: parking-backend
    spec:
      containers:
      - name: backend
        image: parking-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/reservations
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/reservations
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: parking-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort