apiVersion: apps/v1
kind: Deployment
metadata:
  name: parking-frontend
  labels:
    app: parking-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parking-frontend
  template:
    metadata:
      labels:
        app: parking-frontend
    spec:
      containers:
      - name: frontend
        image: parking-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://backend-service:5000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: parking-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort